// Action pool for "Now What?" section - 60 actionable items
export interface ActionEntry {
  title: string;
  stat: string;
  voice: string;
}

export const ACTION_POOL: ActionEntry[] = [
  { title: "Change What You Eat", stat: "Shifting one meal a day from beef to plant-based saves 1,590 kg of CO₂ per year.", voice: "That's more than giving up your car for six months. And it starts at dinner tonight." },
  { title: "Stop Wasting Food", stat: "The average household throws away 30% of the food it buys — roughly $1,800 per year.", voice: "The easiest environmental action is buying less of what you already throw away." },
  { title: "Rethink How You Move", stat: "One transatlantic flight produces 1.6 tonnes of CO₂ — more than the average person in 56 countries produces in an entire year.", voice: "You don't have to stop flying. But you should know what it costs." },
  { title: "Choose Where Your Money Goes", stat: "Moving $10,000 from a standard fund to a fossil-fuel-free fund avoids roughly 1.5 tonnes of CO₂ per year.", voice: "Your money works 24/7. Make sure it's not working against you." },
  { title: "Talk About It", stat: "Research shows social influence is the single strongest driver of behavior change — stronger than facts, fear, or policy.", voice: "The most powerful thing you can do right now is send this page to someone." },
  { title: "Switch Your Electricity", stat: "Switching to a renewable energy provider cuts your home's carbon footprint by up to 80%.", voice: "It takes one phone call. Most people never make it." },
  { title: "Fix the Leaks", stat: "A single dripping faucet wastes 11,000 liters of water per year.", voice: "Multiply that by 100 million households and you've got a crisis made of laziness." },
  { title: "Unplug the Vampires", stat: "Standby electronics consume 5-10% of your home's energy — roughly $100 per year doing nothing.", voice: "Your TV is costing you money right now. It's not even on." },
  { title: "Check Your Bank", stat: "The world's 60 largest banks have pumped $5.5 trillion into fossil fuels since the Paris Agreement.", voice: "Your savings account might be funding what you marched against." },
  { title: "Buy Less, But Better", stat: "The fashion industry produces 10% of global carbon emissions — more than aviation and shipping combined.", voice: "The most sustainable shirt is the one you already own." },
  { title: "Tip the Balance", stat: "Donating $50 to a high-impact climate charity offsets roughly 5 tonnes of CO₂.", voice: "That's what most people produce in two months. For the price of dinner." },
  { title: "Reclaim One Hour", stat: "The average person spends 2.5 hours per day on social media — that's 38 full days per year.", voice: "Imagine what you'd build with 38 days back." },
  { title: "Delete What You Don't Need", stat: "Stored data consumes energy 24/7. The average person's cloud storage generates 200 kg of CO₂ per year.", voice: "Your old photos are warming the planet. Slowly, but constantly." },
  { title: "Search Smarter", stat: "A single AI query uses 10x the energy of a Google search.", voice: "Ask better questions. Ask fewer of them." },
  { title: "Vote Like the Planet Depends on It", stat: "Environmental policy is decided by the people who show up. In most elections, 40% don't.", voice: "Skipping one election does more damage than a year of plastic straws." },
  { title: "Feed One More Person", stat: "Volunteering 2 hours per month at a food bank rescues roughly 200 kg of food per year from landfill.", voice: "That's 400 meals. For 24 hours of your year." },
  { title: "Teach a Kid", stat: "Children who learn about climate science before age 12 are 3x more likely to adopt sustainable behaviors as adults.", voice: "The most important climate technology is a curious 8-year-old." },
  { title: "Walk the Short Ones", stat: "Replacing car trips under 2 miles with walking eliminates roughly 0.5 tonnes of CO₂ per year.", voice: "It's also the easiest way to add 7 years to your life. The data on that is settled." },
  { title: "Sleep Like It Matters", stat: "Sleep deprivation costs the global economy $411 billion per year and increases personal carbon footprint through impaired decision-making.", voice: "Tired people buy more, waste more, and drive more. Rest is an environmental act." },
  { title: "Grow One Thing", stat: "A single home garden can offset 10 kg of CO₂ per year and reduce household food waste by 25%.", voice: "It doesn't have to be much. One tomato plant changes how you see food." },
  { title: "Take Shorter Showers", stat: "Cutting 2 minutes off your shower saves 30 liters each time — roughly 11,000 liters per year.", voice: "That's enough drinking water for one person for 15 years." },
  { title: "Turn Off the Tap", stat: "Leaving the faucet running while brushing your teeth wastes 12 liters per session.", voice: "Twice a day, 365 days. You do the math." },
  { title: "Eat Less Beef for the Water", stat: "A single beef burger requires 2,500 liters of water to produce. A veggie burger takes 150.", voice: "Forget the carbon for a second. The water math is worse." },
  { title: "Check Your Toilet", stat: "A running toilet can waste 750 liters per day without you noticing.", voice: "The most expensive sound in your house is the one you've stopped hearing." },
  { title: "Collect the Rain", stat: "A single rain barrel captures 5,000 liters per year — enough to maintain a small garden.", voice: "The sky is literally giving you free water. Take it." },
  { title: "Refuse the Bag", stat: "The average plastic bag is used for 12 minutes and takes 500 years to decompose.", voice: "Twelve minutes of convenience. Five centuries of consequence." },
  { title: "Repair Before Replacing", stat: "Extending the life of a product by just 9 months reduces its carbon footprint by 20-30%.", voice: "The throwaway instinct is trained, not natural. Untrain it." },
  { title: "Compost Your Scraps", stat: "Home composting diverts 150 kg of waste from landfill per year and reduces methane emissions.", voice: "Rotting food in a landfill produces methane. Rotting food in a compost bin produces soil. Same food. Different ending." },
  { title: "Ditch Single-Use", stat: "A reusable water bottle replaces 156 plastic bottles per year. A reusable coffee cup replaces 500 disposable cups.", voice: "It's not sacrifice. It's just carrying a bottle." },
  { title: "Buy Secondhand First", stat: "Purchasing a used item instead of new saves an average of 82% of the energy that went into its production.", voice: "Someone else already broke it in for you. That's not a downgrade." },
  { title: "Read the Label", stat: "Products with palm oil contribute to 8% of global deforestation.", voice: "It's in your shampoo, your cereal, and your ice cream. You can't avoid what you can't see." },
  { title: "Combine Your Errands", stat: "Consolidating three separate car trips into one saves roughly 3 kg of CO₂ per week.", voice: "That's 150 kg per year. Just from thinking ahead." },
  { title: "Work From Home One Day", stat: "Skipping one commute day per week reduces your transport emissions by 20%.", voice: "The most productive thing your car can do is stay parked." },
  { title: "Inflate Your Tires", stat: "Properly inflated tires improve fuel efficiency by 3% — saving roughly 100 kg of CO₂ and $150 per year.", voice: "Three minutes with an air pump. That's the whole intervention." },
  { title: "Take the Train", stat: "A train trip produces 80% less CO₂ per mile than driving alone.", voice: "It's also the only commute where you can read a book, but that's a separate argument." },
  { title: "Fly Direct", stat: "Layover flights produce up to 50% more emissions because takeoffs burn the most fuel.", voice: "If you're going to fly, at least make the math less bad." },
  { title: "Unsubscribe From Everything", stat: "Spam and marketing emails generate roughly 0.3 grams of CO₂ each. Multiply by 107 trillion emails per year.", voice: "Every inbox you clean is a micro power plant you shut off." },
  { title: "Stream Less in 4K", stat: "Streaming video in 4K uses 7x the energy of standard definition.", voice: "Your eyes can't tell the difference from the couch. The grid can." },
  { title: "Turn Off Autoplay", stat: "The average person watches 60% more content with autoplay on than without.", voice: "The algorithm isn't curating. It's consuming your time and the server's electricity." },
  { title: "Use Dark Mode", stat: "Dark mode on OLED screens uses up to 60% less power.", voice: "Your phone lasts longer. The planet does too. Tiny, but real." },
  { title: "Clean Your Inbox", stat: "10,000 stored emails consume roughly the same energy as 40 plastic bags per year.", voice: "Digital clutter is still clutter. It's just invisible." },
  { title: "Switch to LEDs", stat: "Replacing 10 incandescent bulbs with LEDs saves 500 kg of CO₂ per year.", voice: "The bulbs pay for themselves in 4 months. After that, you're profiting." },
  { title: "Lower the Thermostat by 1 Degree", stat: "Each degree Celsius you drop saves roughly 300 kg of CO₂ per year.", voice: "Put on a sweater. It's the cheapest climate policy on Earth." },
  { title: "Wash Clothes Cold", stat: "90% of a washing machine's energy goes to heating water. Cold wash eliminates that.", voice: "Your clothes don't know the difference. Your energy bill does." },
  { title: "Hang Dry Your Laundry", stat: "A dryer produces roughly 2.4 kg of CO₂ per load. Air drying produces zero.", voice: "The sun has been drying clothes for 200,000 years. It's proven technology." },
  { title: "Seal the Drafts", stat: "Air leaks account for 25-30% of heating and cooling energy loss in the average home.", voice: "You're not heating your house. You're heating your neighborhood." },
  { title: "Write One Letter", stat: "Elected officials weigh one handwritten letter as equivalent to the opinion of 1,000 constituents.", voice: "A stamp costs less than a dollar. It represents a thousand people." },
  { title: "Show Up to One Meeting", stat: "Local zoning and planning meetings — where energy, transit, and housing decisions actually happen — average less than 20 attendees.", voice: "Democracy works when people are in the room. The room is usually empty." },
  { title: "Support Local Journalism", stat: "Local newspapers have lost 60% of their revenue since 2000. Without them, corruption and environmental violations go unreported.", voice: "Nobody investigates a polluter for free." },
  { title: "Join One Thing", stat: "People who belong to a community organization are 3x more likely to take sustained environmental action than solo actors.", voice: "Individual action is good. Collective action is how things actually change." },
  { title: "Ask One Question at Work", stat: "70% of corporate emissions come from supply chains that employees never question.", voice: "You don't have to be the CEO. You just have to ask where things come from." },
  { title: "Share This With One Person", stat: "Behavioral research shows a personal recommendation from someone you trust is 4x more persuasive than any advertisement.", voice: "You're not sharing a website. You're sharing a perspective." },
  { title: "Spend 20 Minutes Outside", stat: "Research shows 20 minutes in nature reduces cortisol by 28% and increases pro-environmental behavior for up to a week.", voice: "You protect what you know. You know what you experience." },
  { title: "Learn One Species", stat: "The average person can name 1,000 brand logos and fewer than 10 local plant species.", voice: "That ratio says everything about what we've been paying attention to." },
  { title: "Plant a Native Species", stat: "Native plants support 10-50x more pollinators than ornamental species.", voice: "Your garden is either a rest stop or a dead zone. The plant you choose decides." },
  { title: "Leave the Leaves", stat: "Fallen leaves shelter overwintering pollinators and add 3-5 cm of organic matter to soil per year.", voice: "The tidiest lawn in the neighborhood is also the most ecologically dead." },
  { title: "Talk to Your Kids About Money", stat: "Consumer habits are formed by age 7. Children who learn about waste and value early buy 23% less impulsively as adults.", voice: "You're not just raising a child. You're shaping a consumer — or not." },
  { title: "Cook One Meal Together", stat: "Households that cook together waste 40% less food than those that eat separately.", voice: "It's not about the recipe. It's about seeing what goes in and what gets thrown away." },
  { title: "Start a No New Things Month", stat: "The average household buys 60+ new items per month. Pausing for one month saves roughly $500 and 200 kg of CO₂.", voice: "You won't miss most of it. That's the uncomfortable part." },
  { title: "Have the Conversation", stat: "Only 35% of Americans discuss climate change even occasionally. The number one reason? They think nobody else wants to.", voice: "Everyone's waiting for someone else to bring it up. Be the someone." },
];
